---
# Apply common roles to all deconst hosts at once.

- hosts: deconst-all
  gather_facts: no
  vars_files:
  - vars.yml
  - credentials.yml
  roles:
  - defunctzombie.coreos-bootstrap

- hosts: deconst-all
  vars_files:
  - vars.yml
  - credentials.yml
  roles:
  - common
