---
# Provision hosts and other necessary infrastructure.

- name: provision hosts
  hosts: local
  connection: local
  gather_facts: no
  vars_files:
  - vars.yml
  - credentials.yml
  tasks:

  - name: build host
    rax:
      state: present
      name: deconst-build
      group: deconst-build
      count: 1
      exact_count: yes
      auto_increment: no
      image: "{{ image_id_ubuntu_1404 }}"
      flavor: general1-2
      key_name: "{{ rackspace_keyname }}"
      wait: yes
    register: rax_build

  - name: add newly provisioned hosts to the correct groups
    add_host:
      name: "{{ rax_build.instances[0].name }}"
      ansible_ssh_host: "{{ rax_build.instances[0].rax_accessipv4 }}"
      ansible_ssh_user: root
      groups: deconst-build
    when: rax_build.action == "create"


- name: pause to ensure SSH is up
  hosts: deconst-all
  gather_facts: no
  tasks:

  - name: ensure SSH is listening on all hosts
    local_action: wait_for host={{ hostvars[inventory_hostname].ansible_ssh_host }} port=22 state=started
