---
# Provision hosts and other necessary infrastructure.

- name: provision hosts
  hosts: local
  connection: local
  gather_facts: no
  vars_files:
  - vars.yml
  - credentials.yml
  tasks:

  - name: worker hosts
    rax:
      state: present
      name: deconst-worker-%03d
      group: deconst-worker
      count: "{{ worker_count }}"
      exact_count: yes
      image: "{{ image_id_coreos_beta }}"
      flavor: "{{ worker_flavor }}"
      key_name: "{{ rackspace_keyname }}"
      wait: yes
    register: rax_build_workers

  - name: add newly provisioned workers to the correct groups
    add_host:
      name: "{{ item.name }}"
      ansible_ssh_host: "{{ item.rax_accessipv4 }}"
      fresh_host: yes
      groups: deconst-worker
    when: rax_build_workers.action == "create"
    with_items: rax_build_workers.success

  - name: identify full cluster rebuilds
    set_fact:
      fresh_cluster: "{{ (rax_build_workers.action == 'create' and rax_build_workers.success | length == worker_count) | bool }}"

  - name: presenter load balancer
    rax_clb:
      name: deconst-presenter
      port: "{{ presenter_lb_port }}"
      wait: yes
      state: present
    register: clb_presenter
    tags: network

  - name: locate the load balancer VIP
    set_fact: clb_vip_id={{ clb_presenter.balancer.virtual_ips[0].id }}
    tags: network

  - name: content service load balancer
    rax_clb:
      name: deconst-content-service
      port: "{{ content_service_lb_port }}"
      vip_id: "{{ clb_vip_id }}"
      wait: yes
      state: present
    register: clb_content_service
    tags: network

  - name: webhook service load balancer
    rax_clb:
      name: deconst-webhook-service
      port: "{{ webhook_service_lb_port }}"
      vip_id: "{{ clb_vip_id }}"
      wait: yes
      state: present
    register: clb_webhook_service
    tags: network

  - name: force the generation of a new token for a fresh cluster
    file: path=.etcd_cluster_token state=absent
    when: fresh_cluster

  - name: etcd cluster token
    set_fact:
      etcd_cluster_token: "{{ lookup('password', '.etcd_cluster_token length=20') }}"

- name: collect SSH public keys of newly launched hosts
  hosts: local
  connection: local
  gather_facts: no
  vars_files:
  - vars.yml
  - credentials.yml
  tasks:

  - name: trust newly launched hosts
    lineinfile:
      dest: "{{ lookup('env', 'HOME') }}/.ssh/known_hosts"
      create: yes
      state: present
      line: "{{ lookup('pipe', 'ssh-keyscan -t rsa ' + item.rax_accessipv4 )}}"
      regexp: "^{{ item.rax_accessipv4 }}"
    with_items: rax_build_workers.success
