---
# Provision hosts and other necessary infrastructure.

- name: provision hosts
  hosts: local
  connection: local
  gather_facts: no
  vars_files:
  - vars.yml
  - credentials.yml
  tasks:

  - name: worker hosts
    rax:
      state: present
      name: deconst-worker-%03d
      group: deconst-worker
      count: "{{ worker_count }}"
      exact_count: yes
      image: "{{ image_id_coreos_beta }}"
      flavor: general1-2
      key_name: "{{ rackspace_keyname }}"
      user_data: "{{ lookup('template', 'templates/cloud_config.yml.j2') }}"
      wait: yes
    register: rax_build_workers

  - name: add newly provisioned workers to the correct groups
    add_host:
      name: "{{ item.name }}"
      ansible_ssh_host: "{{ item.rax_accessipv4 }}"
      groups: deconst-worker
    when: rax_build_workers.action == "create"
    with_items: rax_build_workers.instances

- name: pause to ensure SSH is up
  hosts: deconst-all
  gather_facts: no
  tasks:

  - name: ensure SSH is listening on all hosts
    local_action: wait_for host={{ hostvars[inventory_hostname].ansible_ssh_host }} port=22 state=started
