---
# Provision hosts and other necessary infrastructure.

- name: provision hosts
  hosts: local
  connection: local
  gather_facts: no
  vars_files:
  - vars.yml
  - credentials.yml
  tasks:

  - name: worker hosts
    rax:
      state: present
      name: deconst-{{ instance }}-worker-{{ deployment }}-%03d
      group: deconst-{{ instance }}-worker-{{ deployment }}
      count: "{{ worker_count }}"
      exact_count: yes
      image: "{{ image_coreos_beta }}"
      flavor: "{{ worker_flavor }}"
      key_name: "{{ rackspace_keyname }}"
      wait: yes
    register: rax_build_workers
    tags: always

  - name: add newly provisioned workers to the correct groups
    add_host:
      name: "{{ item.name }}"
      ansible_ssh_host: "{{ item.rax_accessipv4 }}"
      fresh_host: yes
      groups: deconst-{{ instance }}-worker-{{ deployment }}
    when: rax_build_workers.action == "create"
    with_items: rax_build_workers.success
    tags: always

  - name: add all worker hosts to the correct groups
    add_host:
      name: "{{ item.name }}"
      groups: deconst-worker
    with_items: rax_build_workers.instances
    tags: always

  - name: identify full worker cluster rebuilds
    set_fact:
      fresh_worker_cluster: "{{ (rax_build_workers.action == 'create' and rax_build_workers.success | length == worker_count) | bool }}"

  - name: elasticsearch hosts
    rax:
      state: present
      name: deconst-{{ instance }}-elastic-{{ deployment }}-%03d
      group: deconst-{{ instance }}-elastic-{{ deployment }}
      count: "{{ elastic_count }}"
      exact_count: yes
      image: "{{ image_coreos_beta }}"
      flavor: "{{ elastic_flavor }}"
      key_name: "{{ rackspace_keyname }}"
      wait: yes
    register: rax_build_elastic
    tags: elastic

  - name: add newly provisioned elastic hosts to the correct groups
    add_host:
      name: "{{ item.name }}"
      ansible_ssh_host: "{{ item.rax_accessipv4 }}"
      fresh_host: yes
      groups: deconst-{{ instance }}-elastic-{{ deployment }}
    when: rax_build_elastic.action == "create"
    with_items: rax_build_elastic.success
    tags: always

  - name: add all elasticsearch hosts to the correct groups
    add_host:
      name: "{{ item.name }}"
      ansible_ssh_host: "{{ item.rax_accessipv4 }}"
      groups: deconst-elastic,deconst-{{ instance }}-elastic-{{ deployment }}
    with_items: rax_build_elastic.instances
    tags: elastic

  - name: identify full elastic cluster rebuilds
    set_fact:
      fresh_elastic_cluster: "{{ (rax_build_elastic.action == 'create' and rax_build_elastic.success | length == elastic_count) | bool }}"

  - name: presenter load balancer
    rax_clb:
      name: deconst-{{ instance }}-presenter
      port: "{{ presenter_lb_port }}"
      wait: yes
      state: present
    register: clb_presenter

  - name: locate the load balancer VIP
    set_fact: clb_vip_id={{ clb_presenter.balancer.virtual_ips[0].id }}

  - name: content service load balancer
    rax_clb:
      name: deconst-{{ instance }}-content
      port: "{{ content_service_lb_port }}"
      vip_id: "{{ clb_vip_id }}"
      wait: yes
      state: present
    register: clb_content_service

  - name: force the generation of a new token for a fresh worker cluster
    file: path=.etcd_cluster_token state=absent
    when: fresh_worker_cluster

  - name: etcd cluster token
    set_fact:
      etcd_cluster_token: "{{ lookup('password', '.etcd_cluster_token length=20') }}"

- name: collect SSH public keys of newly launched hosts
  hosts: local
  connection: local
  gather_facts: no
  vars_files:
  - vars.yml
  - credentials.yml
  tasks:

  - name: trust newly launched hosts
    lineinfile:
      dest: "{{ lookup('env', 'HOME') }}/.ssh/known_hosts"
      create: yes
      state: present
      line: "{{ lookup('pipe', 'ssh-keyscan -t rsa ' + item.rax_accessipv4 )}}"
      regexp: "^{{ item.rax_accessipv4 }}"
    with_items: "{{ rax_build_workers.success|union(rax_build_elastic.success) }}"
