---
# Coordinate an orderly restart of the cluster if necessary.
#
# The variables in the "when:" clause are populated by the tasks in the worker role. This task
# has been split out from the main role so that it can be performed serially.

- hosts: deconst-worker
  vars_files:
  - vars.yml
  - credentials.yml
  serial: 1
  tasks:

  # The service module is smart: when you use it with with_nested or with_items, it consolidates
  # actions into a single invocation of the underlying binary (systemctl). However, this is exactly
  # what we *don't* want here, because then all of the services do the charging herd thing on their
  # load balancers.
  #
  # Instead, manually restart each pod together by invoking systemctl directly.
  - name: restart service pods
    command: systemctl restart deconst-content@{{ item }}.service deconst-presenter@{{ item }}.service deconst-nginx@{{ item }}.service
    with_items: pod_names
    when: service_pod_restart|default(false)|bool
    sudo: yes
    tags: restart

  - name: restart presenters only
    command: systemctl restart deconst-presenter@{{ item }}.service deconst-nginx@{{ item }}.service
    with_items: pod_names
    when: presenter_restart|default(false)|bool
    sudo: yes
    tags: restart

  - name: restart nginx only
    command: systemctl restart deconst-nginx@{{ item }}.service
    with_items: pod_names
    when: nginx_restart|default(false)|bool
    sudo: yes
    tags: restart

  - name: restart logstash-forwarder
    service: name=logstash-forwarder state=restarted
    when: logstash_forwarder_restart|default(false)|bool
    sudo: yes
    tags: restart

- hosts: deconst-elastic
  serial: 1
  tasks:

  - name: restart logstash
    service: name=deconst-logstash.service state=restarted
    when: logstash_restart|default(false)|bool
    sudo: yes
    tags: restart

- hosts: deconst-build
  serial: 1
  tasks:

  - name: restart strider
    command: |
      systemctl restart
        deconst-strider.service deconst-nginx-build.service
    when: strider_restart|default(false)|bool
    sudo: yes
    tags: restart

  - name: restart staging
    command: |
      systemctl restart
        deconst-staging-content@1.service deconst-staging-presenter@1.service
        deconst-staging-nginx@1.service
    when: staging_restart|default(false)|bool
    sudo: yes
    tags: restart
