---
# Primary playbook. Include other playbooks with appropriate tags.

- include: provision.yml tags=provision

- include: common.yml tags=common

- include: elastic.yml tags=elastic

- include: worker.yml tags=worker

- include: restart.yml tags=restart
