---
# Primary playbook. Include other playbooks with appropriate tags.

- include: provision.yml tags=provision

- include: common.yml tags=common

- include: certificates.yml tags=certificates

- include: elastic.yml tags=elastic

- include: worker.yml tags=worker

- include: staging.yml tags=staging

- include: build.yml tags=build

- include: restart.yml tags=restart
