---

- name: presenter
  docker:
    name: presenter
    image: deconst/presenter
    pull: always
    state: reloaded
    links:
    - "content-service:content-service"
    - "mapping-service:mapping-service"
    env:
      CONTENT_SERVICE_URL: http://content-service:{{ content_service_port }}/
      MAPPING_SERVICE_URL: http://mapping-service:{{ mapping_service_port }}/
      PRESENTED_URL_DOMAIN: "{{ presented_url_domain }}"
      PRESENTER_LOG_LEVEL: "{{ presenter_log_level }}"
    ports:
    - "80:8080"
    restart_policy: always
