---

# Run the mapping service and presentation layer.

- name: content service
  docker:
    name: content-service
    image: deconst/content-service
    pull: always
    state: reloaded
    env:
      RACKSPACE_USERNAME: "{{ rackspace_username }}"
      RACKSPACE_APIKEY: "{{ rackspace_api_key }}"
      RACKSPACE_REGION: "{{ rackspace_region }}"
      RACKSPACE_CONTAINER: "{{ content_container }}"
    ports:
    - "8080:8080"
    restart_policy: always

- name: mapping service
  docker:
    name: mapping-service
    image: deconst/mapping-service
    pull: always
    state: reloaded
    env:
      MAPREPO_URL: "{{ map_repository_url }}"
      MAPREPO_BRANCH: "{{ map_repository_branch }}"
    ports:
    - "9999:9999"
    restart_policy: always

- name: presenter
  docker:
    name: presenter
    image: deconst/presenter
    pull: always
    state: reloaded
    links:
    - "content-service:content-service"
    - "mapping-service:mapping-service"
    env:
      CONTENT_SERVICE_URL: http://content-service:8080/
      MAPPING_SERVICE_URL: http://mapping-service:9999/
    ports:
    - "80:8080"
    restart_policy: always
