---

- name: presenter
  docker:
    name: presenter
    image: deconst/presenter
    pull: always
    state: reloaded
    links:
    - "content-service:content-service"
    - "mapping-service:mapping-service"
    env:
      CONTENT_SERVICE_URL: http://content-service:8080/
      MAPPING_SERVICE_URL: http://mapping-service:9999/
    ports:
    - "80:8080"
    restart_policy: always
