---

- name: content service
  docker:
    name: content-service
    image: deconst/content-service
    pull: always
    state: reloaded
    env:
      RACKSPACE_USERNAME: "{{ rackspace_username }}"
      RACKSPACE_APIKEY: "{{ rackspace_api_key }}"
      RACKSPACE_REGION: "{{ rackspace_region }}"
      RACKSPACE_CONTAINER: "{{ content_container }}"
      CONTENT_LOG_LEVEL: "{{ content_log_level }}"
    ports:
    - "{{ content_service_port }}:8080"
    restart_policy: always
