#!/bin/bash

set -ueo pipefail

ROOT=$(cd $(dirname $0)/.. && pwd)

source ${ROOT}/script/include/credentials.sh
source ${ROOT}/script/include/setup.sh

setup_inventory

INSTANCE=$(credential instance)
DEPLOYMENT=$(credential deployment)

PATTERN=deconst-all
case "${1:-}" in
  worker)
    shift
    PATTERN=deconst-${INSTANCE}-worker-${DEPLOYMENT}
    ;;
  elastic)
    shift
    PATTERN=deconst-${INSTANCE}-elastic-${DEPLOYMENT}
    ;;
esac

exec ansible ${PATTERN} -i ${ROOT}/inventory "$@"
