#!/bin/bash

set -ueo pipefail

ROOT=$(cd $(dirname $0)/.. && pwd)

[ -f ${ROOT}/env ] || {
  cat <<EOM 1>&2
Environment variables not found. Please copy and customize the example file:
  cp ${ROOT}/env.example ${ROOT}/env
  \${EDITOR} ${ROOT}/env
EOM
  exit 1
}

source ${ROOT}/env

export CONTENT_STORE_URL=http://$(docker port deconst_content_lb 80)/
export CONTENT_STORE_APIKEY=$ADMIN_APIKEY
export CONTENT_STORE_TLS_VERIFY="false"
export TRAVIS_PULL_REQUEST="false"
export NODE_TLS_REJECT_UNAUTHORIZED="0"

docker run -it --rm \
  --env CONTENT_STORE_URL=${CONTENT_STORE_URL} \
  --env CONTENT_STORE_APIKEY=${CONTENT_STORE_APIKEY} \
  --env NODE_TLS_REJECT_UNAUTHORIZED=${NODE_TLS_REJECT_UNAUTHORIZED} \
  --env TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST} \
  --volume /var/control-repo \
  --entrypoint "/bin/sh" \
  --user root \
  quay.io/deconst/preparer-asset \
  -c "apk add --update git; git clone https://github.com/deconst/deconst-docs-control.git /var/control-repo; /usr/src/app/script/entrypoint"
