#!/bin/bash

set -ueo pipefail

ROOT=$(cd $(dirname $0)/.. && pwd)

source ${ROOT}/script/include/credentials.sh

INSTANCE=$(credential instance)
SRC=${ROOT}/credentials.yml
DEST=${1:-${ROOT}}

[ -d "${DEST}" ] && {
  DEST="${DEST}/credentials-${INSTANCE}.yml.enc"
}

exec openssl enc -md sha256 -aes-256-cbc -in ${SRC} -out ${DEST}
