#!/bin/bash

set -ueo pipefail

ROOT=$(cd $(dirname $0)/.. && pwd)

source ${ROOT}/script/include/credentials.sh

INSTANCE=$(credential instance)
SRC=${ROOT}/credentials.yml
DEST=${1:-${ROOT}}

[ -d "${DEST}" ] && {
  DEST="${DEST}/credentials-${INSTANCE}.yml.enc"
}

PASSOPT=""
[ -n "${PASSPHRASE}" ] && PASSOPT="-pass env:PASSPHRASE"

exec openssl enc -md sha256 -aes-256-cbc ${PASSOPT} -in ${SRC} -out ${DEST}
