#!/usr/bin/env python

import os
import sys
import requests

from include import utils
utils.log_warnings()

from include import credentials

if len(sys.argv) != 2:
    print "Usage: {} <keyname>".format(sys.argv[0])
    sys.exit(1)
keyname = sys.argv[1]

content_store_url = credentials.content_store_url()

params = {'named': keyname}
headers = credentials.admin_auth_header()

r = requests.post("{}/keys".format(content_store_url),
                  headers=headers, params=params)
r.raise_for_status()

key_doc = r.json()
key = key_doc["apikey"]

print "# Generated API key:"
print
print 'export CONTENT_STORE_APIKEY="{}"'.format(key)
print
