#!/usr/bin/env python

import re
import os
import sys
import requests

from include import utils
utils.log_warnings()

import pyrax

if len(sys.argv) != 2:
    print "Usage: {} <keyname>".format(sys.argv[0])
    sys.exit(1)

keyname = sys.argv[1]

admin_apikey = re.sub(r'\s+', "", utils.credential("content_admin_apikey"))
content_store_url = utils.content_store_url()

params = {'named': keyname}
headers = {'Authorization': 'deconst apikey="{}"'.format(admin_apikey)}

r = requests.post("{}/keys".format(content_store_url),
                  headers=headers, params=params)
r.raise_for_status()

key_doc = r.json()
key = key_doc["apikey"]

print "# Generated API key:"
print
print 'export CONTENT_STORE_APIKEY="{}"'.format(key)
print
