#!/bin/bash

set -ueo pipefail

ROOT=$(cd $(dirname $0)/.. && pwd)

source ${ROOT}/script/include/credentials.sh

export MONGO_USERNAME=$(credential mongodb_username)
export MONGO_PASSWORD=$(credential mongodb_password)
export MONGO_HOST=$(credential mongodb_host | sed -E -e 's/[^,]+,//g')

exec docker run -it --rm mongo:2.6 mongo ${MONGO_HOST} -u ${MONGO_USERNAME} -p ${MONGO_PASSWORD}
