#!/usr/bin/env python


### How To ###
# Start the certbot container on the worker server:
#  $ docker start 29b5fa284256
# run this script
# To run a dry run
#  $ docker exec 194794766a35 certbot certonly --manual --preferred-challenges dns --cert-name deconst.horse -d secure.deconst.horse -d build.deconst.horse -d staging.deconst.horse -d content.staging.deconst.horse --staging --dry-run -m laura.santamaria@rackspace.com --agree-tos --non-interactive --text
# To run it for real, remote the --staging and --dry-run
#get the info:
#  $docker exec (number) tail -f /var/log/letsencrypt/letsencrypt.log
#  $df -h


from include import utils
utils.log_warnings()

import subprocess
import pyrax
import yaml
import os

# Uncomment lines 12 - 30 to implement request debugging.
# import requests
# import logging
#
# # Enabling debugging at http.client level (requests->urllib3->http.client)
# # you will see the REQUEST, including HEADERS and DATA, and RESPONSE with HEADERS but without DATA.
# # the only thing missing will be the response.body which is not logged.
# try:  # for Python 3
#     from http.client import HTTPConnection
# except ImportError:
#     from httplib import HTTPConnection
# HTTPConnection.debuglevel = 1
#
# # you need to initialize logging, otherwise you will not see anything from
# # requests
# logging.basicConfig()
# logging.getLogger().setLevel(logging.DEBUG)
# requests_log = logging.getLogger("requests.packages.urllib3")
# requests_log.setLevel(logging.DEBUG)
# requests_log.propagate = True
#
#
# Get our bearings on the filesystem.
root = os.path.realpath(os.path.join(os.path.dirname(__file__), ".."))

cert_path = os.path.join(os.getcwd(), 'le_certificates')
subprocess.check_call(['rm', '-rf', cert_path])
os.makedirs(cert_path)

# Collect credentials and authenticate.

with open(os.path.join(root, "credentials.yml")) as credfile:
    creds = yaml.load(credfile)
rackspace_username = creds["rackspace_username"]
rackspace_apikey = creds["rackspace_api_key"]
rackspace_region = creds["rackspace_region"]
instance_name = creds["instance"]

pyrax.set_setting("identity_type", "rackspace")
pyrax.set_credentials(rackspace_username, rackspace_apikey)
cs = pyrax.connect_to_cloudservers(region=rackspace_region)
clb = pyrax.connect_to_cloud_loadbalancers(region=rackspace_region)

# Find the load balancer.

print "Finding load balancer."
presenter_lb_name = "deconst-{}-presenter".format(instance_name)
presenter_lb = None
for lb in clb.list():
    if lb.name == presenter_lb_name:
        presenter_lb = lb

if not presenter_lb:
    print "Unable to locate the presenter load balancer!"
    sys.exit(1)

# Remove all nodes from the CLB.
print "Removing nodes from CLB."
if hasattr(presenter_lb, 'nodes'):
    for node in presenter_lb.nodes:
        node.delete()
        pyrax.utils.wait_until(presenter_lb, "status",
                               "ACTIVE", interval=1, attempts=30)

# Launch a certbot container on one of the servers with port 443 published.
print "Creating certbot container."
# container_id = subprocess.check_output(
#     ['docker', 'run', '-d',
#         '-p', '443:443', '-p', '80:80',
#         '--entrypoint', 'sleep',
#         'quay.io/letsencrypt/letsencrypt', '1d']).strip()
container_id = "5f9a17ab74a82e8a3354dc77ecebfbf262cf794375e3441ee0920a5713c11e23"
# print "container id is " + container_id
# docker_host = subprocess.check_output('echo', '$DOCKER_HOST').strip()
# print "docker host is " + docker_host

# Add a single node to the CLB pointing to the certbot container.
print "Adding certbot node to CLB."
container_ip = '10.176.194.79'
presenter_lb.add_nodes(
    [clb.Node(address=container_ip, port=443, condition="ENABLED")])
pyrax.utils.wait_until(presenter_lb, "status", "ACTIVE",
                       interval=1, attempts=30)

print "waiting for you to run stuff"
raw_input("Press Enter to continue...")


# Exec the certbot command to issue a new certificate.
# print "Issuing new certificate."
# subprocess.check_call(
#     ['docker', 'exec', container_id,
#      'certbot', 'certonly',
#      '--standalone',
#      '--email', 'laura.santamaria@rackspace.com', '--agree-tos',
#      '--noninteractive',
#      '-d', 'deconst.horse'])

# Copy the issued certificates from the container.
# print "Copying issued certificates."
# for pemfile in ('privkey.pem', 'fullchain.pem', 'chain.pem', 'cert.pem'):
#     subprocess.check_call(
#         ['docker', 'cp', '--follow-link',
#          '{}:/etc/letsencrypt/live/deconst.horse/{}'.format(
#              container_id, pemfile),
#          cert_path])

# Run script/lb to put the right nodes back in place.
print "Correcting load balancer nodes."
subprocess.check_call(['script/lb', '--fix', '--verbose'])

# Clean up certbot container
print "You need to clean up certbot container."
# subprocess.check_call(['docker', 'stop', container_id])
# subprocess.check_call(['docker', 'rm', container_id])
