#!/bin/bash

set -ueo pipefail

ROOT=$(cd $(dirname $0)/.. && pwd)

source ${ROOT}/script/include/credentials.sh
source ${ROOT}/script/include/setup.sh

setup_inventory
setup_galaxy

cd ${ROOT}
exec ansible-playbook -i ${ROOT}/inventory ${ROOT}/update.yml $*
