apiVersion: v1
kind: Service
metadata:
  namespace: deconst
  name: mongo
  labels:
    name: mongo
spec:
  ports:
    - port: 27017
      targetPort: mongo
  selector:
    name: mongo
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: deconst
  name: mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:2.6
          ports:
            - name: mongo
              containerPort: 27017
