---

- name: mapping service
  docker:
    name: mapping-service
    image: deconst/mapping-service
    pull: always
    state: reloaded
    env:
      CONTROL_REPO_URL: "{{ control_repository_url }}"
      CONTROL_REPO_BRANCH: "{{ control_repository_branch }}"
      MAP_LOG_LEVEL: "{{ map_log_level }}"
    ports:
    - "9999:9999"
    restart_policy: always
