---

- name: pod name ranges
  set_fact:
    pod_names: "[{% for i in range(1, pod_count + 1) %}{{ i }}{% if not loop.last %},{% endif %}{% endfor %}]"

- name: environment variables
  template:
    src: deconst-environment.j2
    dest: /etc/deconst/environment.sh
    owner: root
    group: root
    mode: 0600
  sudo: yes
  register: environment

- name: utility scripts
  copy:
    src: scripts/{{ item }}
    dest: /opt/bin/{{ item }}
    owner: root
    group: root
    mode: 0755
  with_items:
  - record-port
  - peekaboo-up
  - peekaboo-down
  sudo: yes

- name: peekaboo binary
  get_url: dest=/opt/bin/peekaboo url=https://github.com/rgbkrk/peekaboo/releases/download/v0.0.1-alpha/peekaboo
  sudo: yes

- name: peekaboo is executable
  file: path=/opt/bin/peekaboo mode=0755
  sudo: yes

- name: ensure containers are up to date
  command: /opt/bin/multipull rgbkrk/peekaboo {% for image in worker_containers %}quay.io/deconst/{{ image }} {% endfor %}
  register: worker_pulls
  failed_when: worker_pulls.rc == 1
  changed_when: worker_pulls.rc == 2
  tags: update

- name: show the pull result
  debug: var=worker_pulls.stdout_lines

- name: unit files
  copy:
    src: services/{{ item }}@.service
    dest: /etc/systemd/system/{{ item }}@.service
    owner: root
    group: root
    mode: 0644
  with_items: worker_services
  register: worker_units
  sudo: yes

- name: control repository
  git:
    repo: "{{ control_repository_url }}"
    version: "{{ control_repository_branch }}"
    dest: /var/deconst/control
    force: yes
  sudo: yes
  tags: control

- name: reload unit files
  command: systemctl daemon-reload
  when: worker_units | changed
  sudo: yes

- name: container services
  service: name={{ item[1] }}@{{ item[0] }}.service state=started enabled=true
  with_nested:
  - pod_names
  - worker_services
  register: worker_service_results
  sudo: yes
