---

- name: pod name ranges
  set_fact:
    pod_names: "[{% for i in range(1, pod_count + 1) %}{{ i }}{% if not loop.last %},{% endif %}{% endfor %}]"
  tags: always

- name: service environment variables
  template:
    src: deconst-service-environment.j2
    dest: /etc/deconst/service-environment.sh
    owner: root
    group: root
    mode: 0600
  sudo: yes
  register: service_environment

- name: nginx environment variables
  template:
    src: deconst-nginx-environment.j2
    dest: /etc/deconst/nginx-environment.sh
    owner: root
    group: root
    mode: 0600
  sudo: yes
  register: nginx_environment

- name: TLS credentials
  template:
    src: "{{ item }}.j2"
    dest: /etc/deconst/ssl/{{ item }}
    owner: root
    group: root
    mode: 0600
  sudo: yes
  register: certificate
  with_items:
  - certificate.pem
  - certificate_key.pem

- name: logstash-forwarder configuration
  template:
    src: logstash-forwarder-config.json.j2
    dest: /etc/deconst/logstash-forwarder-config.json
    owner: root
    group: root
    mode: 0644
  sudo: yes
  register: lf_config

- name: logstash-forwarder binary
  get_url: dest=/opt/bin/logstash-forwarder url=https://download.elastic.co/logstash-forwarder/binaries/logstash-forwarder_linux_amd64
  register: lf_binary
  sudo: yes

- name: binaries are executable
  file: path=/opt/bin/{{ item }} mode=0755
  with_items:
  - logstash-forwarder
  sudo: yes

- name: ensure containers are up to date
  command: /opt/bin/multipull {% for image in worker_containers %}quay.io/deconst/{{ image }} {% endfor %}
  register: worker_pulls
  failed_when: worker_pulls.rc == 1
  changed_when: worker_pulls.rc == 2
  tags: update

- name: show the pull result
  debug: var=worker_pulls.stdout_lines

- name: deconst service unit files
  copy:
    src: services/{{ item }}@.service
    dest: /etc/systemd/system/{{ item }}@.service
    owner: root
    group: root
    mode: 0644
  with_items: worker_services
  register: worker_units
  sudo: yes

- name: logstash forwarder unit file
  copy:
    src: services/logstash-forwarder.service
    dest: /etc/systemd/system/logstash-forwarder.service
    owner: root
    group: root
    mode: 0644
  register: lf_unit
  sudo: yes

- name: reload unit files
  command: systemctl daemon-reload
  when: worker_units|changed or lf_unit|changed
  sudo: yes

- name: container service pods
  service: name={{ item[1] }}@{{ item[0] }}.service state=started enabled=true
  with_nested:
  - pod_names
  - worker_services
  register: worker_service_results
  sudo: yes

- name: logstash-forwarder service
  service: name=logstash-forwarder.service state=started enabled=true
  register: lf_service_result
  sudo: yes

- name: compute restart control vars
  set_fact:
    service_pod_restart: >
      {{ (nginx_environment|changed or service_environment|changed or worker_pulls|changed or worker_units|changed) and not worker_service_results|changed }}
    logstash_forwarder_restart: >
      {{ (lf_binary|changed or lf_config|changed or lf_unit|changed) and not lf_service_result|changed }}
