---

- name: iptables rules
  template: src=rules-save.j2 dest=/var/lib/iptables/rules-save
  sudo: yes
  register: firewall_rules

- name: enable the iptables service
  service: name=iptables-restore.service enabled=yes
  sudo: yes
