---

- name: necessary directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
  - /etc/deconst
  - /etc/deconst/ssl
  - /var/deconst/ports
  - /opt/bin
  sudo: yes

- name: docker-py
  pip: name=docker-py state=present version=1.1.0

- name: systemd-docker binary
  get_url: dest=/opt/bin/systemd-docker force=yes url=https://9616cfffc9f266c74f07-b0b61db18139e69b9a725d06797c5b61.ssl.cf5.rackcdn.com/systemd-docker-f894d629146c3fd97ba5de77053a08671951d626ca9f0238f1463d90e9465703
  sudo: yes

- name: systemd-docker is executable
  file: path=/opt/bin/systemd-docker mode=0755
  sudo: yes
