---

- name: dns servers
  copy:
    dest: /etc/systemd/resolved.conf
    src: resolved.conf
    owner: root
    group: root
    mode: 0644
  register: dns_configuration
  sudo: yes

- name: kick systemd-resolved
  service: name=systemd-resolved state=restarted
  when: dns_configuration | changed
  sudo: yes

- name: necessary directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
  - /etc/deconst
  - /etc/deconst/ssl
  - /var/deconst/ports
  - /opt/bin
  sudo: yes

- name: docker-py
  pip: name=docker-py state=present version=1.1.0

- name: systemd-docker binary
  get_url: dest=/opt/bin/systemd-docker force=yes url=https://9616cfffc9f266c74f07-b0b61db18139e69b9a725d06797c5b61.ssl.cf5.rackcdn.com/systemd-docker-f894d629146c3fd97ba5de77053a08671951d626ca9f0238f1463d90e9465703
  sudo: yes

- name: peekaboo binary
  get_url: dest=/opt/bin/peekaboo url=https://github.com/rgbkrk/peekaboo/releases/download/v0.0.1-alpha/peekaboo
  sudo: yes

- name: binaries are executable
  file: path=/opt/bin/{{ item }} mode=0755
  with_items:
  - systemd-docker
  - peekaboo
  sudo: yes
