---

- name: disable password authentication over SSH
  copy: src=sshd_config dest=/etc/ssh/sshd_config owner=root group=root mode=0644
  sudo: yes

- name: trust github's public key
  lineinfile:
    dest: /etc/ssh/ssh_known_hosts
    create: yes
    state: present
    line: "{{ github_ssh_pubkey | replace(' ', '') | trim }}"
    regexp: "^github\\.com"
  sudo: yes

- name: trust administrator ssh keys
  shell: echo '{{ item.pubkey }}' | update-ssh-keys -a {{ item.name }}
  with_items: admin_ssh_pubkeys
  tags: keys
